### ISSUE TITLE
upper bound on bytestring

### ISSUE THREAD

**Issue by clinty** [stbuehler/haskell-nettle#11]
```
[__3] rejecting: bytestring-0.11.3.1/installed-0.11.3.1 (conflict: nettle =>
bytestring>=0.10.8 && <0.11)
[__3] skipping: bytestring-0.11.3.1, bytestring-0.11.3.0, bytestring-0.11.2.0,
bytestring-0.11.1.0, bytestring-0.11.0.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=0.10.8 &&
<0.11' from 'nettle')
```

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a matching revision: https://hackage.haskell.org/package/nettle-0.3.0/revisions/

**Comment by clinty** [comment]
Also bytestring 0.12

**Comment by stbuehler** [comment]
Hi. I haven't been using haskell in quite some time (not even as powerful calculator, because ghc requires way too much disk space), and haven't been working on this package either.

I'd be happy to pass owernship of this package (not sure if https://wiki.haskell.org/Abandoning_a_package would help with this).

**Comment by clinty** [comment]
@stbuehler I'm willing to do minimal minor upkeep like this if you want to empower Hackage username ClintAdams

**Comment by stbuehler** [comment]
Sounds good, thanks.
